# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5896fffe4c31bd0f5068e0e1f83752fca54bfe1c2fb9ece06a9e8801f137081388933ed3c79152c1072ff7edc4d9e87e21699a54ae08504042cd1baa8e52db28

test:
  secret_key_base: 10401bc8736288d8c83e1748f9d5c828cecd5967a234959a377a9278a284a644483fede0f34b11b5fdf0db7d9d1dfb1c030a33da0fb6289377cf746c787823ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
